[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization", 
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Payloads"
]

[customizations.installer.kickstart]
contents = """
# 1. Configurações de Localização
#lang pt_BR.UTF-8
#keyboard br-abnt2
#timezone America/Sao_Paulo

# 2. Particionamento Dinâmico (O Esquema Supremo)
clearpart --all --initlabel
zerombr

# Boot EFI / BIOS
reqpart --add-boot

# Raiz (/) em EXT4 - 24 GB Fixos. 
part / --fstype=ext4 --size=24576

# Partição física gigante pegando TODO o resto do disco (--grow)
part btrfs.1 --size=1000 --grow

# Cria o Pool Btrfs em cima dessa partição gigante
btrfs none --label=gearos_data btrfs.1

# Subvolume /var (Supremo)
btrfs /var --subvol --name=var gearos_data

# Subvolume /home
btrfs /home --subvol --name=home gearos_data

# 3. Comportamento do Instalador
graphical
reboot
"""
